### ISSUE TITLE
Problem with the camera

### ISSUE THREAD

**Issue by N1K0232** [marcominerva/VisionPlayground#13]
Hi, I just gave a look to the published version of the website and i discovered a problem. The website asked me to use the camera but it doesn't work.
I'm attaching a screenshot of the problem. As you can see the camera box shows a black box with a disabled camera. If i click the camera button, the system takes the photo but the result i get is: "a white and black logo (61.73%)".
This problem persists even if i refresh or i reload the application.

Is this issue only on my side?

![Screenshot 2024-06-11 212721](https://github.com/marcominerva/VisionPlayground/assets/60029977/de526414-2984-4dee-ba1a-3fb41462af8a)
![image](https://github.com/marcominerva/VisionPlayground/assets/60029977/a259b239-e5fd-4964-a478-208ae7ead65a)

**Comment by marcominerva** [comment]
Probably your browser settings are restricting the usage of the camera. Try with InPrivate mode and, if the issue still occurs, make a test with another browser, if you can.

**Comment by N1K0232** [comment]
I tried with both solutions and still it doesn't work. Tomorrow I'll try fix this problem on my browser
If I succeed I'll let you know on discord to avoid to send lots of replies here in this section

**Comment by N1K0232** [comment]
I tried many times and i solved the problem. It was my browser issue
